
title:  Khanh N. Dang
baseurl: "/~khanh" # the subpath of your site, e.g. /blog
url: "https://u-aizu.ac.jp" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - README.md
   - Makefile


# For generating the menu
menu:

- title: Research
  url: research.html

- title: Publication
  url: pub.html

- title: Teaching
  url: teaching.html

- title:  Service
  url: service.html

- title: Student
  url: grp_mem.html

# - title: Mentoring
#   url: mentor.html

- title: Contact
  url: contact.html
